name: My First Workflow

#trigger
on: [push]


# jobs
jobs: 
  #job name
  my-first-workflow:
    #OS that this workflow will be runnning on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps: 
    - name: echo the date
      run: echo "The current time and date in Github is $(date)"